server:
    port: 8083
    context-path: /ui
    session:
      cookie:
        name: UI2SESSION
security:
  basic:
    enabled: false

spring:
  redis:
    host: 119.28.23.209
    port: 6379
    password: redis1234
